<a href="https://colab.research.google.com/github/nandu-21/Daily-assingment/blob/main/day_2assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Function to perform matrix multiplication
def matrix_multiply(A, B):
    return np.dot(A, B)

# Example matrices
A = np.array([[1, 2],
              [3, 3]])
B = np.array([[2, 5],
              [7, 5]])

# Perform multiplication
result = matrix_multiply(A, B)
print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("Matrix Multiplication Result:\n", result)

Matrix A:
 [[1 2]
 [3 3]]
Matrix B:
 [[2 5]
 [7 5]]
Matrix Multiplication Result:
 [[16 15]
 [27 30]]


In [3]:
data = [5, 10, 15, 20, 25]
